apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  selector:
    app: nginx # Selects Pods with the label 'app: nginx'
  ports:
    - protocol: TCP
      port: 80 # The port the Service exposes
      targetPort: 80 # The port on the Pods that the Service forwards traffic to
  type: LoadBalancer # Or NodePort, LoadBalancer